singleQuote: true
tabWidth: 2
trailingComma: all
overrides:
  - files: ['*.ts', '*.tsx', '*.mts', '*.js', '*.mjs', '*.cjs']
    options:
      tabWidth: 4
      jsxSingleQuote: true
plugins: [prettier-plugin-organize-imports]
